version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flask_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 3s

  flask_api:
    build: ./flask_api
    container_name: flask_api
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_NAME: flask_db
      DB_USER: flask_user
      DB_PASSWORD: flask_password
    depends_on:
      - mysql
    networks:
      - flask_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask_api
    networks:
      - flask_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 3s

volumes:
  mysql_data:

networks:
  flask_network:
